### ISSUE TITLE
Supported Jetty versions

### ISSUE THREAD

**Issue by md5** [appropriate/docker-jetty#34]
I just noticed that there are 9.4.0.M0 and 9.3.10.M0 versions of Jetty after seeing [a comment](https://github.com/appropriate/docker-jetty/issues/30#issuecomment-225283574) from @joakime on #30. I also recall @jmcc0nn3ll commenting that Jetty 9.2 is considered EOL (see [here](https://github.com/appropriate/docker-jetty/pull/32#issuecomment-221319444)).

I wanted to open this issue in anticipation of the update to Jetty 9.4 to see which versions we should actually support.

**Comment by joakime** [comment]
any Jetty release with `#.#.#.M#` is a milestone / unstable / beta release.

Jetty 9.4 will introduce a few things: easier configuration for embedded users (implemented), javax.websocket 1.1 support (being worked on now), websocket proxy support (planned), including support for JDK9 and it's new JVM level ALPN (implemented).

Jetty 10.x (also underway in master branch) will be Servlet 4.x

**Comment by jmcc0nn3ll** [comment]
I also have the striped down jetty-home distribution almost ready to go, probably M1 which we can use in Alpine to shrink the size a bit.

**Comment by md5** [comment]
@joakime Thanks for the explanation about the `M*` releases. I know that they are milestone releases and I don't generally build docker images for them, although I did build one for 9.3.0.M2. When those images _are_ built, they are only tagged with their full version number, so if we were to build a 9.4 image before the official release, it would not be tagged `jetty:9.4`, but only `jetty:9.4.0.M#`.

@jmcc0nn3ll That's great to hear! That may actually be a good reason to start early on a milestone-based `jetty:9.4.0.M#` image once those changes land in a milestone, since it will greatly simplify the `Dockerfile`.

**Comment by md5** [comment]
As for a `jre9` image to complement the Java 9 support in Jetty 9.4, that's going to depend on https://github.com/docker-library/openjdk/issues/29. I haven't checked up on the status of OpenJDK 9 packaging in Debian for a while.

**Comment by jmcc0nn3ll** [comment]
sounds good, I'll help get it wired up when we push it out, maybe a week or
two

## 

jesse mcconnell
jesse.mcconnell@gmail.com

**Comment by md5** [comment]
@jmcc0nn3ll FYI, I pushed up a [`jetty-9.4`](https://github.com/appropriate/docker-jetty/tree/jetty-9.4) branch based on `9.4.0.M0`. I don't plan to submit a `jetty:9.4` image to Docker Hub, but if you want to make any changes you can target any PRs there.

**Comment by jmcc0nn3ll** [comment]
sure thing, plan is to have a new 9.4 milestone build in the next week or
three and then I'll get a PR there for you

## 

jesse mcconnell
jesse.mcconnell@gmail.com

**Comment by md5** [comment]
FYI, I just updated the `jetty-9.4` branch to Jetty 9.4.0.RC0.

@jmcc0nn3ll Did you make any progress with the slimmed down `JETTY_HOME` you mentioned in your earlier comment?

Also, I noticed that https://github.com/docker-library/openjdk/issues/29 was closed about a month ago (and the actual image was added back in November 2015 and I commented on it...), so there is now an `openjdk:9` image we can use as a base. Which versions do we want to update to have a `jre9` variant?

**Comment by md5** [comment]
FWIW, it looks like there is not an Alpine variant of the JRE 9 `openjdk` image.

**Comment by jmcc0nn3ll** [comment]
@md5 yes, there is now a org.eclipse.jetty:jetty-home artifact that contains as stripped down distribution as we can make and still have all the nuts and bolts of Jetty bundled up.  We now use it in the jetty-distribution artifact as the starting point and bring in the elements of the demo-base, etc.  I have been planning on giving a PR with this but figured I would wait for RC1 which is targeted for this next week, thinking is that will be structurally very much like what we'll be moving forward with.

**Comment by md5** [comment]
Sounds great
